//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public System.Guid COMP_ID { get; set; }
        public string COMP_NO { get; set; }
        public string COMP_CODE { get; set; }
        public string COMP_NAME { get; set; }
        public string DEPARTMENT { get; set; }
        public System.Guid STATUS_LOOKUPID { get; set; }
        public System.Guid LINEOFBIZ_LOOKUPID { get; set; }
        public System.Guid CHANNEL_LOOKUPID { get; set; }
        public string SALES_PERSON { get; set; }
        public System.Guid COMP_SIZE_LOOKUPID { get; set; }
        public System.Guid CURRENCY_LOOKUPID { get; set; }
        public System.Guid PAYMENTTERM_LOOKUPID { get; set; }
        public System.Guid CREDITLIMIT_LOOKUPID { get; set; }
        public System.Guid PRICEBAND_LOOKUPID { get; set; }
        public System.Guid DISCOUNTBAND_LOOKUPID { get; set; }
        public System.Guid TAXCODE_LOOKUPID { get; set; }
        public System.Guid TAXCODE2_LOOKUPID { get; set; }
        public System.Guid TAXCODE3_LOOKUPID { get; set; }
        public System.Guid SHIPMENTTERM_LOOKUPID { get; set; }
        public System.Guid COMP_BILL_LOC_ID { get; set; }
        public System.Guid COMP_SHIP_LOC_ID { get; set; }
        public System.Guid COMP_TYPE_LOOKUPID { get; set; }
        public System.Guid OWNERSHIP_LOOKUPID { get; set; }
        public string COMP_EMAIL { get; set; }
        public string COMP_WEBSITE { get; set; }
        public Nullable<System.Guid> RATING_ID { get; set; }
        public int YEARS_OF_ESTABLISHMENT { get; set; }
        public int NO_OF_EMPLOYEES_OFFICE { get; set; }
        public int NO_OF_EMPLOYEES_FACTORY { get; set; }
        public Nullable<double> REVENUE { get; set; }
        public Nullable<double> TURN_OVER { get; set; }
        public Nullable<double> SALES { get; set; }
        public string CAPACITY_DAILY { get; set; }
        public string CAPACITY_MONTHLY { get; set; }
        public string CAPACITY_YEARLY { get; set; }
        public bool ISACTIVE { get; set; }
        public Nullable<System.Guid> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public System.Guid CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
