//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTXPROD
    {
        public System.Guid CUST_ID { get; set; }
        public System.Guid PRD_ID { get; set; }
        public int ID { get; set; }
    }
}
