//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.CUST_STATUS_HISTORY = new HashSet<CUST_STATUS_HISTORY>();
            this.QUOTATIONs = new HashSet<QUOTATION>();
        }
    
        public System.Guid CUST_ID { get; set; }
        public System.Guid COMP_ID { get; set; }
        public string CUST_NO { get; set; }
        public string CUST_CODE { get; set; }
        public string CUST_NAME { get; set; }
        public bool ISVENDOR { get; set; }
        public string LEGAL_NAME { get; set; }
        public string DEPARTMENT { get; set; }
        public string COMPANY_RELATIONSHIP { get; set; }
        public System.Guid STATUS_LKPID { get; set; }
        public Nullable<System.Guid> LINEOFBIZ_LKPID { get; set; }
        public Nullable<System.Guid> LOB_CATEGORY_LKPID { get; set; }
        public Nullable<System.Guid> COMPANY_GROUP_CODE_LKPID { get; set; }
        public Nullable<System.Guid> SALESCHNL_REFERENCE_LKPID { get; set; }
        public string SALES_PERSON { get; set; }
        public string COMP_SIZE { get; set; }
        public System.Guid CURRENCY_LKPID { get; set; }
        public Nullable<System.Guid> SHIPMENTTERM_LKPID { get; set; }
        public Nullable<System.Guid> PAYMENTTERM_LKPID { get; set; }
        public Nullable<System.Guid> CREDITLIMIT_LKPID { get; set; }
        public Nullable<System.Guid> PRICEBAND_LKPID { get; set; }
        public Nullable<System.Guid> DISCOUNTBAND_LKPID { get; set; }
        public string AUTO_BANDING { get; set; }
        public System.Guid TAXCODE1_LKPID { get; set; }
        public Nullable<System.Guid> TAXCODE2_LKPID { get; set; }
        public Nullable<System.Guid> TAXCODE3_LKPID { get; set; }
        public System.Guid CUST_BILL_LOC_ID { get; set; }
        public System.Guid CUST_SHIP_LOC_ID { get; set; }
        public System.Guid CUST_TYPE_LKPID { get; set; }
        public System.Guid OWNERSHIP_LKPID { get; set; }
        public string COMPANY_EMAIL { get; set; }
        public string COMPANY_WEBSITE { get; set; }
        public Nullable<System.Guid> RATING_ID { get; set; }
        public int YEARS_OF_ESTABLISHMENT { get; set; }
        public int NO_OF_EMPLOYEES_OFFICE { get; set; }
        public int NO_OF_EMPLOYEES_FACTORY { get; set; }
        public Nullable<double> REVENUE { get; set; }
        public Nullable<double> TURN_OVER { get; set; }
        public Nullable<double> SALES { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public string SHIPMENT_METHOD { get; set; }
        public string CALL_PREFERENCES { get; set; }
        public string CREDIT_CHECK { get; set; }
        public string CONTRACT { get; set; }
        public string MSA { get; set; }
        public string SLA { get; set; }
        public string DECLARATION { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMPANY_TYPE { get; set; }
        public string OWNERSHIP { get; set; }
        public string CAPACITY_DAILY { get; set; }
        public string CAPACITY_MONTHLY { get; set; }
        public string CAPACITY_YEARLY { get; set; }
        public string CONTACT_PERSON { get; set; }
        public bool ISACTIVE { get; set; }
        public Nullable<System.Guid> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public System.Guid CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST_STATUS_HISTORY> CUST_STATUS_HISTORY { get; set; }
        public virtual RATING_MASTER RATING_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUOTATION> QUOTATIONs { get; set; }
    }
}
