//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCEPTION_LOGGING
    {
        public System.Guid LOG_ID { get; set; }
        public string EXCEPTION_MSG { get; set; }
        public string EXCEPTION_TYPE { get; set; }
        public string EXCEPTION_SOURCE { get; set; }
        public string EXCEPTION_PAGEDETAILS { get; set; }
        public string EXCEPTION_URL { get; set; }
        public Nullable<System.DateTime> EXEPTION_DATETIME { get; set; }
        public bool ISACTIVE { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public System.Guid CREATED_BY { get; set; }
    }
}
