//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCATION_MASTER()
        {
            this.CONTACT_DETAILS = new HashSet<CONTACT_DETAILS>();
            this.PURCHASE_ORDER = new HashSet<PURCHASE_ORDER>();
        }
    
        public System.Guid LOC_ID { get; set; }
        public string LOC_CODE { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string LOCATION_SHORT_NAME { get; set; }
        public string LOC_ADDRESS { get; set; }
        public string LOC_CITY { get; set; }
        public string LOC_STATE { get; set; }
        public string LOC_COUNTRY { get; set; }
        public string LOC_ZIPCODE { get; set; }
        public string TIME_ZONE { get; set; }
        public string GEO_LOC_LATITUDE { get; set; }
        public string GEO_LOC_LONGITUDE { get; set; }
        public bool ISACTIVE { get; set; }
        public Nullable<System.Guid> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public System.Guid CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_DETAILS> CONTACT_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_ORDER> PURCHASE_ORDER { get; set; }
    }
}
