//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.QUOTATIONs = new HashSet<QUOTATION>();
            this.WORKORDERs = new HashSet<WORKORDER>();
        }
    
        public System.Guid PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_CATEGORY { get; set; }
        public string PRODUCT_VARIANT { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public Nullable<int> PRODUCT_DIMENSIONS_LENGTH { get; set; }
        public Nullable<int> PRODUCT_DIMENSIONS_BREADTH { get; set; }
        public Nullable<int> PRODUCT_DIMENSIONS_WIDTH { get; set; }
        public Nullable<int> PRODUCT_DIMENSIONSA { get; set; }
        public Nullable<int> PRODUCT_DIMENSIONSB { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<bool> ISREPEAT_ORDER { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public Nullable<int> UNIT { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public Nullable<double> LINE_TOTAL { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> GRAND_TOTAL { get; set; }
        public string SPECIAL_REQUESTSA { get; set; }
        public string SPECIAL_REQUESTSB { get; set; }
        public string SPECIAL_REQUESTSC { get; set; }
        public string SPECIAL_REQUESTSD { get; set; }
        public string SPECIAL_REQUESTSE { get; set; }
        public Nullable<System.Guid> PREPARED_BY { get; set; }
        public Nullable<System.Guid> APPROVED_BY { get; set; }
        public string TYPEOF_ORIGINAL { get; set; }
        public Nullable<System.DateTime> DATE_RECEIVED { get; set; }
        public bool ISACTIVE { get; set; }
        public Nullable<System.Guid> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public System.Guid CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUOTATION> QUOTATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKORDER> WORKORDERs { get; set; }
    }
}
