//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ
    {
        public System.Guid RFQ_ID { get; set; }
        public string RFQ_NO { get; set; }
        public string RFQ_NAME { get; set; }
        public string RFQ_DESC { get; set; }
        public string MODEOFRECEIPT { get; set; }
        public string ORIGINATING_COMPANY { get; set; }
        public string ORIGINATING_CONTACTPERSON { get; set; }
        public string ORIGINATING_COMP_PURCHASING_MANAGER { get; set; }
        public string ORIGINATING_COMP_MANAGER { get; set; }
        public string BID_TYPE { get; set; }
        public System.DateTime RFQ_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> CLOSING_DATE { get; set; }
        public string DURATION { get; set; }
        public string DURATION_TIMELINE { get; set; }
        public int NUMBEROFRELEASES { get; set; }
        public System.Guid LOC_ID { get; set; }
        public Nullable<System.Guid> JOB_ID { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_CLIENT_NAME { get; set; }
        public string JOB_LOCATIONA { get; set; }
        public string JOB_LOCATIONB { get; set; }
        public string JOB_LOCATIONC { get; set; }
        public Nullable<bool> ISCUSTOMER_SUPPLIEDDRAWING { get; set; }
        public string DRAWING_SOURCE { get; set; }
        public Nullable<System.Guid> PRODUCT_ID { get; set; }
        public string QUANTITY { get; set; }
        public Nullable<bool> ISREPEAT_ORDER { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public string PRICING_INDICATORSA { get; set; }
        public string PRICING_INDICATORSB { get; set; }
        public string PRICING_INDICATORSC { get; set; }
        public string SPECIAL_REQUESTSA { get; set; }
        public string SPECIAL_REQUESTSB { get; set; }
        public string SPECIAL_REQUESTSC { get; set; }
        public string PREPARED_BY { get; set; }
        public string APPROVED_BY { get; set; }
        public string TYPEOF_ORIGINAL_RFQ { get; set; }
        public string BARCODE { get; set; }
        public string FILE_PATHA { get; set; }
        public string FILE_PATHB { get; set; }
        public Nullable<System.DateTime> DATE_RECEIVED { get; set; }
        public bool ISACTIVE { get; set; }
        public Nullable<System.Guid> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public System.Guid CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
    }
}
