//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserXRole
    {
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
    
        public virtual UserXRole UserXRole1 { get; set; }
        public virtual UserXRole UserXRole2 { get; set; }
    }
}
